services:
  # Base de Datos y Caché
  redis-cache:
    image: redis:alpine
    container_name: zeqium-redis
    ports:
      - "6379:6379"

  zeqium-hotel-db:
    image: postgres:15
    container_name: zeqium-hotel-db
    environment:
      - POSTGRES_USER=zeqium
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hotel_db
    ports:
      - "5432:5432"

  zeqium-police-db:
    image: postgres:15
    container_name: zeqium-police-db
    environment:
      - POSTGRES_USER=zeqium
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=police_db
    ports:
      - "5433:5432"

  # API Gateway (El punto de entrada 100% profesional)
  zeqium-gateway:
    image: nginx:alpine
    container_name: zeqium-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - police-api
      - hotel-api
    networks:
      - default
      - zeqium-net

  # Las APIs como servicios
  police-api:
    build:
      context: .
      dockerfile: ./police-api/Dockerfile
    container_name: police-api
    env_file:
      - ./police-api/.env
    volumes:
      # Inyectamos los certificados en la misma ruta exacta que dice el connection.json
      - /home/mgf00042/Zeqium/blockchain/network/crypto-config:/home/mgf00042/Zeqium/blockchain/network/crypto-config:ro
    depends_on:
      - redis-cache
      - zeqium-police-db
    networks:
      - default
      - zeqium-net

  hotel-api:
    build:
      context: .
      dockerfile: ./hotel-api/Dockerfile
    container_name: hotel-api
    env_file:
      - ./hotel-api/.env
    volumes:
      # Inyectamos los certificados en la misma ruta exacta que dice el connection.json
      - /home/mgf00042/Zeqium/blockchain/network/crypto-config:/home/mgf00042/Zeqium/blockchain/network/crypto-config:ro
    depends_on:
      - redis-cache
      - zeqium-hotel-db
    networks:
      - default
      - zeqium-net

networks:
  zeqium-net:
    external: true
    name: zeqium-net
